// Copyright 2024 ibakha (@ibakha)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */

/* disable debug print */
//#define NO_DEBUG

/* disable print */
//#define NO_PRINT

/* disable action features */
//#define NO_ACTION_LAYER
//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT


/** Split keyboard Config */
#define SERIAL_USART_FULL_DUPLEX
#define SOFT_SERIAL_PIN         A2
// #define SERIAL_USART_TX_PIN A2
#define SERIAL_USART_RX_PIN     A3

#define SERIAL_USART_PIN_SWAP
#define SELECT_SOFT_SERIAL_SPEED    1
#define SERIAL_USART_DRIVER         SD2
#define SERIAL_USART_TX_PAL_MODE    7
#define SERIAL_USART_RX_PAL_MODE    7
#define SERIAL_USART_TIMEOUT        20

#ifdef RGB_MATRIX_ENABLE
/** WS2812 RGB Matrix Config */
#define WS2812_DI_PIN           C2
#define RGB_MATRIX_LED_COUNT    52
#define RGB_MATRIX_SPLIT        {26, 26}

#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL

// #define ENABLE_RGB_MATRIX_TYPING_HEATMAP
// #define ENABLE_RGB_MATRIX_DIGITAL_RAIN

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #define ENABLE_RGB_MATRIX_SPLASH
// #define ENABLE_RGB_MATRIX_MULTISPLASH
// #define ENABLE_RGB_MATRIX_SOLID_SPLASH
// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif

#ifdef OLED_ENABLE
#define OLED_BRIGHTNESS 128

#endif

#ifdef BLUETOOTH_ENABLE
/** Bluetooth config */
#define BLUEFRUIT_LE_RST_PIN B0
#define BLUEFRUIT_LE_CS_PIN  C4
#define BLUEFRUIT_LE_IRQ_PIN C5

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN A5
#define SPI_MISO_PIN A6
#define SPI_MOSI_PIN A7
#define SPI_SCK_PAL_MODE 5
#define SPI_MISO_PAL_MODE 5
#define SPI_MOSI_PAL_MODE 5
#define BATTERY_LEVEL_PIN   A0
#endif

// #ifdef POINTING_DEVICE_ENABLE
// /** Trackball Config*/
// #define SPLIT_POINTING_ENABLE
// #define PMW33XX_CS_PIN  C10
// #define POINTING_DEVICE_SDIO_PIN    A14
// #define POINTING_DEVICE_SCLK_PIN    A15
// #define POINTING_DEVICE_RIGHT
// #endif

